DEVICE_FOLDER := device/meizu/mx4
DEVICE_FOLDER_COMMON := device/meizu/arale

# pull common bits from Ubuntu Edition's repo
-include $(DEVICE_FOLDER_COMMON)/BoardConfigCommon.mk

# make_ext4fs requires numbers in dec format
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216  # 16384 x 1k
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216  # 16384 x 1k
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1375731712  # 1343488 x 1k
BOARD_USERDATAIMAGE_PARTITION_SIZE := 13494648832  # 13178368 * 1k
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_HAS_LARGE_FILESYSTEM := true

# Assert
TARGET_OTA_ASSERT_DEVICE := mx4
# BLISSPOP build
BLISS_BUILD_BLOCK := 1
#BLISS_WIPE_CACHES := 0
TARGET_TC_ROM := 4.9-linaro
TARGET_TC_KERNEL := 4.9-linaro
#BLISSIFY := true
#BLISS_O3 := true
#BLISS_GRAPHITE := false
#BLISS_STRICT := true
#BLISS_KRAIT := true
BLISS_PIPE := true

TARGET_GCC_VERSION_EXP := $(TARGET_TC_ROM)
TARGET_KERNEL_CUSTOM_TOOLCHAIN := $(TARGET_TC_KERNEL)
-include vendor/bliss/config/sm.mk
